### ISSUE TITLE
Add more Zeus pics

### ISSUE THREAD

**Issue by ciampo** [kencanak/zeus-rover#1]
More pics please!

**Comment by kencanak** [comment]
@ciampo 😂. Unfortunately i stopped working on this. Nevertheless here’s non related photos

![D9522272-5B56-4A08-98E7-3B31866B9598](https://user-images.githubusercontent.com/17525206/148883326-f57b607a-3861-417d-89bf-a57b4896b56b.jpeg)
![9FE7F4A4-7CA5-420E-BF65-198D7307D614](https://user-images.githubusercontent.com/17525206/148883340-e0fb6eba-46ea-4080-8a33-ec0866186eb3.jpeg)

**Comment by ciampo** [comment]
That is plenty enough, thank you 🤣
